device=0
# data=data/data_so/fold1/
data=./data/Yelp/
batch=8
n_head=12
n_dis=12
n_layers=2
d_model=1024  # M
d_rnn=128
d_inner=1024 # H 1024
d_k=512   # Mk
d_v=896   # Mv
dropout=0.67834
lr=0.0001
ita=0.037
smooth=0.01836
epoch=30
log=log.txt
coefficient=0.14

CUDA_VISIBLE_DEVICES=$device python Main.py -data $data -batch $batch -n_head $n_head -n_dis $n_dis -ita $ita -n_layers $n_layers -d_model $d_model -d_rnn $d_rnn -d_inner $d_inner -d_k $d_k -d_v $d_v -dropout $dropout -lr $lr -smooth $smooth -epoch $epoch -log $log -coefficient $coefficient
